"""add version to service table

Revision ID: f9caf538394e
Revises: db3c7522dbb3
Create Date: 2020-03-11 16:18:10.735690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9caf538394e'
down_revision = 'db3c7522dbb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('version', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'version')
    # ### end Alembic commands ###
